import type { TopicScore } from './diagnosticGrading'

export interface DiagnosticPdfData {
  testTitle: string
  studentName: string
  dateTaken: string
  correctCount: number
  totalCount: number
  scorePct: number
  topicScores: TopicScore[]
  advice: { topicTitle: string; prepAdvice: string }[]
}

function performanceLabel(pct: number): string {
  if (pct >= 80) return 'Excellent'
  if (pct >= 70) return 'Proficient'
  if (pct >= 60) return 'Developing'
  return 'Needs Improvement'
}

function tierColor(pct: number): [number, number, number] {
  if (pct >= 80) return [16, 185, 129]
  if (pct >= 50) return [245, 158, 11]
  return [239, 68, 68]
}

// Only ever call this from a client-side event handler (never a Server
// Component / module scope) — jsPDF touches browser globals. The dynamic
// import keeps the library out of the initial bundle of every page that
// merely *could* show a download button; it's only fetched on click.
// Deliberately excludes parent contact info — that's a teacher-dashboard-only
// field, not something that belongs in a file the student can redistribute.
export async function downloadDiagnosticPdf(data: DiagnosticPdfData): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()
  const lm = 15
  const pw = 180
  let y = 20

  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, 210, 35, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(data.testTitle, lm, 15)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Student: ${data.studentName}`, lm, 24)
  doc.text(`Date: ${data.dateTaken}`, lm, 31)

  y = 45
  const perf = performanceLabel(data.scorePct)
  doc.setTextColor(0, 0, 0)
  doc.setFillColor(235, 245, 255)
  doc.rect(lm, y, pw, 22, 'F')
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 64, 175)
  doc.text(`Score: ${data.correctCount}/${data.totalCount} (${data.scorePct}%) — ${perf}`, lm + 5, y + 10)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)
  doc.text('Mindspire Lab — Diagnostic Assessment', lm + 5, y + 18)
  y += 30

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Topic Performance', lm, y)
  y += 6
  doc.setDrawColor(200, 200, 200)
  doc.line(lm, y, lm + pw, y)
  y += 5

  for (const t of data.topicScores) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    doc.text(t.topicTitle, lm, y)
    doc.text(`${t.correct}/${t.total} (${t.pct}%)`, lm + pw - 30, y)
    doc.setFillColor(220, 220, 220)
    doc.rect(lm + 65, y - 3.5, 80, 5, 'F')
    const [r, g, b] = tierColor(t.pct)
    doc.setFillColor(r, g, b)
    doc.rect(lm + 65, y - 3.5, Math.round((80 * t.pct) / 100), 5, 'F')
    y += 9
    if (y > 270) { doc.addPage(); y = 20 }
  }

  y += 5
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Before You Start AP Chemistry', lm, y)
  y += 6
  doc.line(lm, y, lm + pw, y)
  y += 6

  if (data.advice.length === 0) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(16, 185, 129)
    doc.text("You're ready for AP Chemistry! No specific weak areas were identified.", lm, y)
    y += 8
  } else {
    for (const a of data.advice) {
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(217, 119, 6)
      const titleLines = doc.splitTextToSize(a.topicTitle, pw)
      doc.text(titleLines, lm, y)
      y += titleLines.length * 4.5 + 1
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(60, 60, 60)
      const adviceLines = doc.splitTextToSize('• ' + a.prepAdvice, pw - 3)
      doc.text(adviceLines, lm + 3, y)
      y += adviceLines.length * 4.5 + 4
      if (y > 270) { doc.addPage(); y = 20 }
    }
  }

  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(`Generated by Mindspire Lab • ${new Date().toLocaleDateString()}`, lm, 290)

  const fname = data.studentName.replace(/\s+/g, '_') || 'Student'
  doc.save(`${data.testTitle.replace(/\s+/g, '_')}_${fname}.pdf`)
}
